export const PERMISSIONS = {
  MANAGE_APP: 'MANAGE_APP',
  MANAGE_MEMBERS: 'MANAGE_MEMBERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_MESSAGES: 'MANAGE_MESSAGES',
  MANAGE_ANNOUNCEMENTS: 'MANAGE_ANNOUNCEMENTS',
  MANAGE_CALLS: 'MANAGE_CALLS',
  CHANGE_BRANDING: 'CHANGE_BRANDING',
  SEND_MESSAGES: 'SEND_MESSAGES',
  MENTION_EVERYONE: 'MENTION_EVERYONE',
  JOIN_CALLS: 'JOIN_CALLS',
  START_CALLS: 'START_CALLS',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_VALUES = Object.values(PERMISSIONS) as [
  Permission,
  ...Permission[],
];
